extends Resource
class_name DG3DGridMapCache

# Baked binary snapshot of a GridMap's cell data.
# Generated by DG3DPainter's "Bake GridMap" button.
# Loaded by DG3DRuntime at game startup to skip runtime rebuild.
@export var cells: PackedInt32Array = []
